version: "3.4"

services:
  oauthServer:
    image: openjdk:8
    container_name: oauth-test-server
    volumes:
      - "./target:/opt/oauth-test-server"
    expose:
      - 9999
    entrypoint: "java -jar /opt/oauth-test-server/oauthserver-0.0.1-SNAPSHOT.jar"
